field: 951dca8a-2309-46fb-8525-f21285de1872
fieldLayouts:
  3d7606d9-f53a-4e30-9287-8a45a966df80:
    tabs:
      -
        elements:
          -
            fieldUid: ed2c08b8-8da5-4535-a7cc-ea8a7ef8890c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ed2c08b8-8da5-4535-a7cc-ea8a7ef8890c:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:af113897-df86-42d5-858d-3a537286716c'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:af113897-df86-42d5-858d-3a537286716c'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageCarousel
name: 'Image Carousel'
sortOrder: 4
