fieldLayouts:
  2aa86186-c832-4646-9a37-6fcf6b543873:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: general
hasUrls: true
name: General
settings:
  path: uploads/general
sortOrder: 1
type: craft\volumes\Local
url: '@web/uploads/general'
